name: Build My Angualr App

on:
  push:
    branches: [ main ]

jobs:
  buid-angualr-app:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v6.0.1
      - name: Setup Node Js
        uses: actions/setup-node@v6.0.0
        with: 
          node-version: 22.x
      - name: Install Dependencies
        run: npm install
      - name: Build angular app
        run: npm run build
